services:
  config-server:
    image: config-server:latest
    build:
      context: ./config-server
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8071:8071"
    environment:
      SECRET_KEY: secretKey
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8071/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
    labels:
      amplicode.image: springboot
    networks:
      backend:

  user-service:
    image: user-service:latest
    build:
      context: ./user-service
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
      to-do-list-db:
        condition: service_healthy
    labels:
      amplicode.image: springboot
    networks:
      backend:

  to-do-list-db:
    image: postgres:17.5
    restart: unless-stopped  # Автоматический перезапуск при падении
    ports:
      - "5432:5432"
    volumes:
      - to-do-list-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: to-do-list-db
    healthcheck: # Проверка готовности БД
      test: [ "CMD-SHELL", "pg_isready -U postgres -d to-do-list-db" ]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      backend:

volumes:
  to-do-list-db:

networks:
  backend:
    driver: bridge