server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://config-server:8071
#  cloud:
#    config:
#      fail-fast: true
#      retry:
#        initial-interval: 2000
#        max-interval: 10000
#        max-attempts: 100