spring:
  datasource:
    url: jdbc:postgresql://to-do-list-db:5432/to-do-list-db
    username: "{cipher}616d40e1b2bf373a696856d1f7bc2a532a3c9ff8682e60f3b0a0a20edbf55612"
    password: "{cipher}616d40e1b2bf373a696856d1f7bc2a532a3c9ff8682e60f3b0a0a20edbf55612"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/db.changelog-master.yml
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: "36b791aaa49dde5129f866e1c6f7ed611b336c1bc37ea95552431aedfd829ab4"
  access-expiration: 86400000  # 24 часа
  refresh-expiration: 604800000  # 7 дней

management:
  tracing:
    sampling:
      probability: 1.0  # 100% трассировка (для разработки)
  endpoints:
    web:
      exposure:
        include: health,info,metrics,tracing
  endpoint:
    health:
      show-details: always

management.zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} [%X{traceId:-},%X{spanId:-}] %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.cloud: DEBUG